[package]
name = "css-to-tw-token"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
lightningcss = { version = "1.0.0-alpha.35", features = ["serde" , "browserslist"]}
serde = "1.0.147"
serde_json = "1.0.87"