use lightningcss::{
    properties::Property,
    rules::{style::StyleRule, CssRule},
    stylesheet::{ParserOptions, PrinterOptions, StyleSheet},
    values::{
        calc::Calc,
        length::{LengthPercentage, LengthPercentageOrAuto, LengthValue},
        percentage::{DimensionPercentage, Percentage},
    },
};
use serde_json;
use std::{fs, path::Path};
mod tailwind_token;
use tailwind_token::TailwindTokenSet;

fn main() {
    let mut income_src = Path::new("./input-src/cdt-toolbar.css");
    read_css_file(income_src);
}

fn read_css_file(file_path: &Path) {
    // let fs::read(file_path).unwrap();

    let file_string = fs::read_to_string(file_path).unwrap();
    let parser_set = StyleSheet::parse(&file_string, ParserOptions::default()).unwrap();

    // println!("{}" , serde_json::to_string_pretty(&parser_set).unwrap());

    for rule in parser_set.rules.0 {
        let mut tw_set = tailwind_token::TailwindTokenSet::new();
        tw_set.set_layer_group(file_path.to_str().unwrap().to_string());

        match rule {
            CssRule::Media(p) => {}
            CssRule::Style(p) => {
                resolve_style(&p, &tw_set);
            }
            CssRule::Import(_) => todo!(),
            CssRule::Keyframes(_) => todo!(),
            CssRule::FontFace(_) => todo!(),
            CssRule::FontPaletteValues(_) => todo!(),
            CssRule::Page(_) => todo!(),
            CssRule::Supports(_) => todo!(),
            CssRule::CounterStyle(_) => todo!(),
            CssRule::Namespace(_) => todo!(),
            CssRule::MozDocument(_) => todo!(),
            CssRule::Nesting(_) => todo!(),
            CssRule::Viewport(_) => todo!(),
            CssRule::CustomMedia(_) => todo!(),
            CssRule::LayerStatement(_) => todo!(),
            CssRule::LayerBlock(_) => todo!(),
            CssRule::Property(_) => todo!(),
            CssRule::Container(_) => todo!(),
            CssRule::Ignored => todo!(),
            CssRule::Unknown(_) => todo!(),
        }
    }
}

fn resolve_style(rule: &StyleRule, mut tw_set: &TailwindTokenSet) {
    for prop in rule.declarations.declarations {
        prop.value_to_css_string(PrinterOptions::default());
        match prop {
            Property::Position(pos) => {
                // prop.property_id().name()
            }
            Property::Padding(p) => {}
            Property::PaddingBlock(p) => {}
            Property::Inset(i) => {
                match i.left {
                    LengthPercentageOrAuto::Auto => todo!(),
                    LengthPercentageOrAuto::LengthPercentage(a) => {
                        // let s: LengthValue = a.into();
                        match a {
                            LengthPercentage::Dimension(s) => {
                                s.to_px().unwrap();
                            }
                            DimensionPercentage::Percentage(_) => todo!(),
                            DimensionPercentage::Calc(_) => todo!(),
                        }
                    }
                }
            }
            Property::BackgroundColor(_) => todo!(),
            Property::BackgroundImage(_) => todo!(),
            Property::BackgroundPositionX(_) => todo!(),
            Property::BackgroundPositionY(_) => todo!(),
            Property::BackgroundPosition(_) => todo!(),
            Property::BackgroundSize(_) => todo!(),
            Property::BackgroundRepeat(_) => todo!(),
            Property::BackgroundAttachment(_) => todo!(),
            Property::BackgroundClip(_, _) => todo!(),
            Property::BackgroundOrigin(_) => todo!(),
            Property::Background(_) => todo!(),
            Property::BoxShadow(_, _) => todo!(),
            Property::Opacity(_) => todo!(),
            Property::Color(_) => todo!(),
            Property::Display(_) => todo!(),
            Property::Visibility(_) => todo!(),
            Property::Width(_) => todo!(),
            Property::Height(_) => todo!(),
            Property::MinWidth(_) => todo!(),
            Property::MinHeight(_) => todo!(),
            Property::MaxWidth(_) => todo!(),
            Property::MaxHeight(_) => todo!(),
            Property::BlockSize(_) => todo!(),
            Property::InlineSize(_) => todo!(),
            Property::MinBlockSize(_) => todo!(),
            Property::MinInlineSize(_) => todo!(),
            Property::MaxBlockSize(_) => todo!(),
            Property::MaxInlineSize(_) => todo!(),
            Property::BoxSizing(_, _) => todo!(),
            Property::Overflow(_) => todo!(),
            Property::OverflowX(_) => todo!(),
            Property::OverflowY(_) => todo!(),
            Property::TextOverflow(_, _) => todo!(),
            Property::Top(_) => todo!(),
            Property::Bottom(_) => todo!(),
            Property::Left(_) => todo!(),
            Property::Right(_) => todo!(),
            Property::InsetBlockStart(_) => todo!(),
            Property::InsetBlockEnd(_) => todo!(),
            Property::InsetInlineStart(_) => todo!(),
            Property::InsetInlineEnd(_) => todo!(),
            Property::InsetBlock(_) => todo!(),
            Property::InsetInline(_) => todo!(),
            Property::BorderSpacing(_) => todo!(),
            Property::BorderTopColor(_) => todo!(),
            Property::BorderBottomColor(_) => todo!(),
            Property::BorderLeftColor(_) => todo!(),
            Property::BorderRightColor(_) => todo!(),
            Property::BorderBlockStartColor(_) => todo!(),
            Property::BorderBlockEndColor(_) => todo!(),
            Property::BorderInlineStartColor(_) => todo!(),
            Property::BorderInlineEndColor(_) => todo!(),
            Property::BorderTopStyle(_) => todo!(),
            Property::BorderBottomStyle(_) => todo!(),
            Property::BorderLeftStyle(_) => todo!(),
            Property::BorderRightStyle(_) => todo!(),
            Property::BorderBlockStartStyle(_) => todo!(),
            Property::BorderBlockEndStyle(_) => todo!(),
            Property::BorderInlineStartStyle(_) => todo!(),
            Property::BorderInlineEndStyle(_) => todo!(),
            Property::BorderTopWidth(_) => todo!(),
            Property::BorderBottomWidth(_) => todo!(),
            Property::BorderLeftWidth(_) => todo!(),
            Property::BorderRightWidth(_) => todo!(),
            Property::BorderBlockStartWidth(_) => todo!(),
            Property::BorderBlockEndWidth(_) => todo!(),
            Property::BorderInlineStartWidth(_) => todo!(),
            Property::BorderInlineEndWidth(_) => todo!(),
            Property::BorderTopLeftRadius(_, _) => todo!(),
            Property::BorderTopRightRadius(_, _) => todo!(),
            Property::BorderBottomLeftRadius(_, _) => todo!(),
            Property::BorderBottomRightRadius(_, _) => todo!(),
            Property::BorderStartStartRadius(_) => todo!(),
            Property::BorderStartEndRadius(_) => todo!(),
            Property::BorderEndStartRadius(_) => todo!(),
            Property::BorderEndEndRadius(_) => todo!(),
            Property::BorderRadius(_, _) => todo!(),
            Property::BorderImageSource(_) => todo!(),
            Property::BorderImageOutset(_) => todo!(),
            Property::BorderImageRepeat(_) => todo!(),
            Property::BorderImageWidth(_) => todo!(),
            Property::BorderImageSlice(_) => todo!(),
            Property::BorderImage(_, _) => todo!(),
            Property::BorderColor(_) => todo!(),
            Property::BorderStyle(_) => todo!(),
            Property::BorderWidth(_) => todo!(),
            Property::BorderBlockColor(_) => todo!(),
            Property::BorderBlockStyle(_) => todo!(),
            Property::BorderBlockWidth(_) => todo!(),
            Property::BorderInlineColor(_) => todo!(),
            Property::BorderInlineStyle(_) => todo!(),
            Property::BorderInlineWidth(_) => todo!(),
            Property::Border(_) => todo!(),
            Property::BorderTop(_) => todo!(),
            Property::BorderBottom(_) => todo!(),
            Property::BorderLeft(_) => todo!(),
            Property::BorderRight(_) => todo!(),
            Property::BorderBlock(_) => todo!(),
            Property::BorderBlockStart(_) => todo!(),
            Property::BorderBlockEnd(_) => todo!(),
            Property::BorderInline(_) => todo!(),
            Property::BorderInlineStart(_) => todo!(),
            Property::BorderInlineEnd(_) => todo!(),
            Property::Outline(_) => todo!(),
            Property::OutlineColor(_) => todo!(),
            Property::OutlineStyle(_) => todo!(),
            Property::OutlineWidth(_) => todo!(),
            Property::FlexDirection(_, _) => todo!(),
            Property::FlexWrap(_, _) => todo!(),
            Property::FlexFlow(_, _) => todo!(),
            Property::FlexGrow(_, _) => todo!(),
            Property::FlexShrink(_, _) => todo!(),
            Property::FlexBasis(_, _) => todo!(),
            Property::Flex(_, _) => todo!(),
            Property::Order(_, _) => todo!(),
            Property::AlignContent(_, _) => todo!(),
            Property::JustifyContent(_, _) => todo!(),
            Property::PlaceContent(_) => todo!(),
            Property::AlignSelf(_, _) => todo!(),
            Property::JustifySelf(_) => todo!(),
            Property::PlaceSelf(_) => todo!(),
            Property::AlignItems(_, _) => todo!(),
            Property::JustifyItems(_) => todo!(),
            Property::PlaceItems(_) => todo!(),
            Property::RowGap(_) => todo!(),
            Property::ColumnGap(_) => todo!(),
            Property::Gap(_) => todo!(),
            Property::BoxOrient(_, _) => todo!(),
            Property::BoxDirection(_, _) => todo!(),
            Property::BoxOrdinalGroup(_, _) => todo!(),
            Property::BoxAlign(_, _) => todo!(),
            Property::BoxFlex(_, _) => todo!(),
            Property::BoxFlexGroup(_, _) => todo!(),
            Property::BoxPack(_, _) => todo!(),
            Property::BoxLines(_, _) => todo!(),
            Property::FlexPack(_, _) => todo!(),
            Property::FlexOrder(_, _) => todo!(),
            Property::FlexAlign(_, _) => todo!(),
            Property::FlexItemAlign(_, _) => todo!(),
            Property::FlexLinePack(_, _) => todo!(),
            Property::FlexPositive(_, _) => todo!(),
            Property::FlexNegative(_, _) => todo!(),
            Property::FlexPreferredSize(_, _) => todo!(),
            Property::GridTemplateColumns(_) => todo!(),
            Property::GridTemplateRows(_) => todo!(),
            Property::GridAutoColumns(_) => todo!(),
            Property::GridAutoRows(_) => todo!(),
            Property::GridAutoFlow(_) => todo!(),
            Property::GridTemplateAreas(_) => todo!(),
            Property::GridTemplate(_) => todo!(),
            Property::Grid(_) => todo!(),
            Property::GridRowStart(_) => todo!(),
            Property::GridRowEnd(_) => todo!(),
            Property::GridColumnStart(_) => todo!(),
            Property::GridColumnEnd(_) => todo!(),
            Property::GridRow(_) => todo!(),
            Property::GridColumn(_) => todo!(),
            Property::GridArea(_) => todo!(),
            Property::MarginTop(_) => todo!(),
            Property::MarginBottom(_) => todo!(),
            Property::MarginLeft(_) => todo!(),
            Property::MarginRight(_) => todo!(),
            Property::MarginBlockStart(_) => todo!(),
            Property::MarginBlockEnd(_) => todo!(),
            Property::MarginInlineStart(_) => todo!(),
            Property::MarginInlineEnd(_) => todo!(),
            Property::MarginBlock(_) => todo!(),
            Property::MarginInline(_) => todo!(),
            Property::Margin(_) => todo!(),
            Property::PaddingTop(_) => todo!(),
            Property::PaddingBottom(_) => todo!(),
            Property::PaddingLeft(_) => todo!(),
            Property::PaddingRight(_) => todo!(),
            Property::PaddingBlockStart(_) => todo!(),
            Property::PaddingBlockEnd(_) => todo!(),
            Property::PaddingInlineStart(_) => todo!(),
            Property::PaddingInlineEnd(_) => todo!(),
            Property::PaddingInline(_) => todo!(),
            Property::ScrollMarginTop(_) => todo!(),
            Property::ScrollMarginBottom(_) => todo!(),
            Property::ScrollMarginLeft(_) => todo!(),
            Property::ScrollMarginRight(_) => todo!(),
            Property::ScrollMarginBlockStart(_) => todo!(),
            Property::ScrollMarginBlockEnd(_) => todo!(),
            Property::ScrollMarginInlineStart(_) => todo!(),
            Property::ScrollMarginInlineEnd(_) => todo!(),
            Property::ScrollMarginBlock(_) => todo!(),
            Property::ScrollMarginInline(_) => todo!(),
            Property::ScrollMargin(_) => todo!(),
            Property::ScrollPaddingTop(_) => todo!(),
            Property::ScrollPaddingBottom(_) => todo!(),
            Property::ScrollPaddingLeft(_) => todo!(),
            Property::ScrollPaddingRight(_) => todo!(),
            Property::ScrollPaddingBlockStart(_) => todo!(),
            Property::ScrollPaddingBlockEnd(_) => todo!(),
            Property::ScrollPaddingInlineStart(_) => todo!(),
            Property::ScrollPaddingInlineEnd(_) => todo!(),
            Property::ScrollPaddingBlock(_) => todo!(),
            Property::ScrollPaddingInline(_) => todo!(),
            Property::ScrollPadding(_) => todo!(),
            Property::FontWeight(_) => todo!(),
            Property::FontSize(_) => todo!(),
            Property::FontStretch(_) => todo!(),
            Property::FontFamily(_) => todo!(),
            Property::FontStyle(_) => todo!(),
            Property::FontVariantCaps(_) => todo!(),
            Property::LineHeight(_) => todo!(),
            Property::Font(_) => todo!(),
            Property::VerticalAlign(_) => todo!(),
            Property::FontPalette(_) => todo!(),
            Property::TransitionProperty(_, _) => todo!(),
            Property::TransitionDuration(_, _) => todo!(),
            Property::TransitionDelay(_, _) => todo!(),
            Property::TransitionTimingFunction(_, _) => todo!(),
            Property::Transition(_, _) => todo!(),
            Property::AnimationName(_, _) => todo!(),
            Property::AnimationDuration(_, _) => todo!(),
            Property::AnimationTimingFunction(_, _) => todo!(),
            Property::AnimationIterationCount(_, _) => todo!(),
            Property::AnimationDirection(_, _) => todo!(),
            Property::AnimationPlayState(_, _) => todo!(),
            Property::AnimationDelay(_, _) => todo!(),
            Property::AnimationFillMode(_, _) => todo!(),
            Property::Animation(_, _) => todo!(),
            Property::Transform(_, _) => todo!(),
            Property::TransformOrigin(_, _) => todo!(),
            Property::TransformStyle(_, _) => todo!(),
            Property::TransformBox(_) => todo!(),
            Property::BackfaceVisibility(_, _) => todo!(),
            Property::Perspective(_, _) => todo!(),
            Property::PerspectiveOrigin(_, _) => todo!(),
            Property::Translate(_) => todo!(),
            Property::Rotate(_) => todo!(),
            Property::Scale(_) => todo!(),
            Property::TextTransform(_) => todo!(),
            Property::WhiteSpace(_) => todo!(),
            Property::TabSize(_, _) => todo!(),
            Property::WordBreak(_) => todo!(),
            Property::LineBreak(_) => todo!(),
            Property::Hyphens(_, _) => todo!(),
            Property::OverflowWrap(_) => todo!(),
            Property::WordWrap(_) => todo!(),
            Property::TextAlign(_) => todo!(),
            Property::TextAlignLast(_, _) => todo!(),
            Property::TextJustify(_) => todo!(),
            Property::WordSpacing(_) => todo!(),
            Property::LetterSpacing(_) => todo!(),
            Property::TextIndent(_) => todo!(),
            Property::TextDecorationLine(_, _) => todo!(),
            Property::TextDecorationStyle(_, _) => todo!(),
            Property::TextDecorationColor(_, _) => todo!(),
            Property::TextDecorationThickness(_) => todo!(),
            Property::TextDecoration(_, _) => todo!(),
            Property::TextDecorationSkipInk(_, _) => todo!(),
            Property::TextEmphasisStyle(_, _) => todo!(),
            Property::TextEmphasisColor(_, _) => todo!(),
            Property::TextEmphasis(_, _) => todo!(),
            Property::TextEmphasisPosition(_, _) => todo!(),
            Property::TextShadow(_) => todo!(),
            Property::BoxDecorationBreak(_, _) => todo!(),
            Property::Resize(_) => todo!(),
            Property::Cursor(_) => todo!(),
            Property::CaretColor(_) => todo!(),
            Property::CaretShape(_) => todo!(),
            Property::Caret(_) => todo!(),
            Property::UserSelect(_, _) => todo!(),
            Property::AccentColor(_) => todo!(),
            Property::Appearance(_, _) => todo!(),
            Property::ListStyleType(_) => todo!(),
            Property::ListStyleImage(_) => todo!(),
            Property::ListStylePosition(_) => todo!(),
            Property::ListStyle(_) => todo!(),
            Property::MarkerSide(_) => todo!(),
            Property::Composes(_) => todo!(),
            Property::Fill(_) => todo!(),
            Property::FillRule(_) => todo!(),
            Property::FillOpacity(_) => todo!(),
            Property::Stroke(_) => todo!(),
            Property::StrokeOpacity(_) => todo!(),
            Property::StrokeWidth(_) => todo!(),
            Property::StrokeLinecap(_) => todo!(),
            Property::StrokeLinejoin(_) => todo!(),
            Property::StrokeMiterlimit(_) => todo!(),
            Property::StrokeDasharray(_) => todo!(),
            Property::StrokeDashoffset(_) => todo!(),
            Property::MarkerStart(_) => todo!(),
            Property::MarkerMid(_) => todo!(),
            Property::MarkerEnd(_) => todo!(),
            Property::Marker(_) => todo!(),
            Property::ColorInterpolation(_) => todo!(),
            Property::ColorInterpolationFilters(_) => todo!(),
            Property::ColorRendering(_) => todo!(),
            Property::ShapeRendering(_) => todo!(),
            Property::TextRendering(_) => todo!(),
            Property::ImageRendering(_) => todo!(),
            Property::ClipPath(_, _) => todo!(),
            Property::ClipRule(_) => todo!(),
            Property::MaskImage(_, _) => todo!(),
            Property::MaskMode(_) => todo!(),
            Property::MaskRepeat(_, _) => todo!(),
            Property::MaskPositionX(_) => todo!(),
            Property::MaskPositionY(_) => todo!(),
            Property::MaskPosition(_, _) => todo!(),
            Property::MaskClip(_, _) => todo!(),
            Property::MaskOrigin(_, _) => todo!(),
            Property::MaskSize(_, _) => todo!(),
            Property::MaskComposite(_) => todo!(),
            Property::MaskType(_) => todo!(),
            Property::Mask(_, _) => todo!(),
            Property::MaskBorderSource(_) => todo!(),
            Property::MaskBorderMode(_) => todo!(),
            Property::MaskBorderSlice(_) => todo!(),
            Property::MaskBorderWidth(_) => todo!(),
            Property::MaskBorderOutset(_) => todo!(),
            Property::MaskBorderRepeat(_) => todo!(),
            Property::MaskBorder(_) => todo!(),
            Property::WebKitMaskComposite(_) => todo!(),
            Property::WebKitMaskSourceType(_, _) => todo!(),
            Property::WebKitMaskBoxImage(_, _) => todo!(),
            Property::WebKitMaskBoxImageSource(_, _) => todo!(),
            Property::WebKitMaskBoxImageSlice(_, _) => todo!(),
            Property::WebKitMaskBoxImageWidth(_, _) => todo!(),
            Property::WebKitMaskBoxImageOutset(_, _) => todo!(),
            Property::WebKitMaskBoxImageRepeat(_, _) => todo!(),
            Property::Filter(_, _) => todo!(),
            Property::BackdropFilter(_, _) => todo!(),
            Property::ZIndex(_) => todo!(),
            Property::ContainerType(_) => todo!(),
            Property::ContainerName(_) => todo!(),
            Property::Container(_) => todo!(),
            Property::Unparsed(_) => todo!(),
            Property::Custom(_) => todo!(),
        }
    }
}
